apiVersion: apps/v1 
kind: Deployment
metadata:
  name: grafana
  labels: 
    app: grafana
    purpose: Task5
    status: Completed
spec:
  selector:
    matchLabels:
      app: grafana
      purpose: Task5
      status: Completed
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grafana
        purpose: Task5
        status: Completed
    spec:
      containers:
      - image: vimal13/grafana
        name: grafana
        ports:
        - containerPort: 3000
          name: grafana
        volumeMounts:
        - name: grafana-persistent-storage
          mountPath: /var/lib/grafana
      volumes:
      - name: grafana-persistent-storage
        persistentVolumeClaim:
          claimName: grafana-pv-claim

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pv-claim
  labels:
    app: grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi          