apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-config
data:
 prometheus.yml: |-
  global:
    scrape_interval: 5s
    evaluation_interval: 5s
  alerting:
    alertmanagers:
    - static_configs:
      - targets: ["192.168.99.100:91111"]
  scrape_configs:
    - job_name: 'prometheus'
    #metrics default path is /metrics
      static_configs:
      - targets: ['localhost:9090']
    - job_name: 'node1'
      static_configs:
      - targets: ['192.168.99.100:9100']
 